// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package proxy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Proxy_Type int32

const (
	Proxy_CONNECT Proxy_Type = 0
	Proxy_SUCCESS Proxy_Type = 1
	Proxy_FAILED  Proxy_Type = 2
)

var Proxy_Type_name = map[int32]string{
	0: "CONNECT",
	1: "SUCCESS",
	2: "FAILED",
}

var Proxy_Type_value = map[string]int32{
	"CONNECT": 0,
	"SUCCESS": 1,
	"FAILED":  2,
}

func (x Proxy_Type) Enum() *Proxy_Type {
	p := new(Proxy_Type)
	*p = x
	return p
}

func (x Proxy_Type) String() string {
	return proto.EnumName(Proxy_Type_name, int32(x))
}

func (x *Proxy_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Proxy_Type_value, data, "Proxy_Type")
	if err != nil {
		return err
	}
	*x = Proxy_Type(value)
	return nil
}

func (Proxy_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0, 0}
}

type Proxy struct {
	Type                 *Proxy_Type `protobuf:"varint,1,opt,name=type,enum=proxy.Proxy_Type" json:"type,omitempty"`
	Protocol             *string     `protobuf:"bytes,2,opt,name=protocol" json:"protocol,omitempty"`
	NodeName             *string     `protobuf:"bytes,3,opt,name=node_name,json=nodeName" json:"node_name,omitempty"`
	Ip                   *string     `protobuf:"bytes,4,opt,name=ip" json:"ip,omitempty"`
	Port                 *int32      `protobuf:"varint,5,opt,name=port" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Proxy) Reset()         { *m = Proxy{} }
func (m *Proxy) String() string { return proto.CompactTextString(m) }
func (*Proxy) ProtoMessage()    {}
func (*Proxy) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *Proxy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proxy.Unmarshal(m, b)
}
func (m *Proxy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proxy.Marshal(b, m, deterministic)
}
func (m *Proxy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proxy.Merge(m, src)
}
func (m *Proxy) XXX_Size() int {
	return xxx_messageInfo_Proxy.Size(m)
}
func (m *Proxy) XXX_DiscardUnknown() {
	xxx_messageInfo_Proxy.DiscardUnknown(m)
}

var xxx_messageInfo_Proxy proto.InternalMessageInfo

func (m *Proxy) GetType() Proxy_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Proxy_CONNECT
}

func (m *Proxy) GetProtocol() string {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return ""
}

func (m *Proxy) GetNodeName() string {
	if m != nil && m.NodeName != nil {
		return *m.NodeName
	}
	return ""
}

func (m *Proxy) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *Proxy) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func init() {
	proto.RegisterEnum("proxy.Proxy_Type", Proxy_Type_name, Proxy_Type_value)
	proto.RegisterType((*Proxy)(nil), "proxy.Proxy")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf) }

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0xaf,
	0xa8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x76, 0x32, 0x72, 0xb1,
	0x06, 0x80, 0x58, 0x42, 0xaa, 0x5c, 0x2c, 0x25, 0x95, 0x05, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x7c, 0x46, 0x82, 0x7a, 0x10, 0xc5, 0x60, 0x39, 0xbd, 0x90, 0xca, 0x82, 0xd4, 0x20, 0xb0, 0xb4,
	0x90, 0x14, 0x17, 0x07, 0xd8, 0x80, 0xe4, 0xfc, 0x1c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20,
	0x38, 0x5f, 0x48, 0x9a, 0x8b, 0x33, 0x2f, 0x3f, 0x25, 0x35, 0x3e, 0x2f, 0x31, 0x37, 0x55, 0x82,
	0x19, 0x22, 0x09, 0x12, 0xf0, 0x4b, 0xcc, 0x4d, 0x15, 0xe2, 0xe3, 0x62, 0xca, 0x2c, 0x90, 0x60,
	0x01, 0x8b, 0x32, 0x65, 0x16, 0x08, 0x09, 0x71, 0xb1, 0x14, 0xe4, 0x17, 0x95, 0x48, 0xb0, 0x2a,
	0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x4a, 0x3a, 0x5c, 0x2c, 0x20, 0xab, 0x84, 0xb8, 0xb9, 0xd8,
	0x9d, 0xfd, 0xfd, 0xfc, 0x5c, 0x9d, 0x43, 0x04, 0x18, 0x40, 0x9c, 0xe0, 0x50, 0x67, 0x67, 0xd7,
	0xe0, 0x60, 0x01, 0x46, 0x21, 0x2e, 0x2e, 0x36, 0x37, 0x47, 0x4f, 0x1f, 0x57, 0x17, 0x01, 0x26,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xa0, 0x6d, 0x56, 0xd0, 0x00, 0x00, 0x00,
}
