apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-edge
  namespace: edgemesh-test
  labels:
    app: hostname-lb-edge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hostname-lb-edge
  template:
    metadata:
      labels:
        app: hostname-lb-edge
    spec:
      containers:
        - name: hostname
          image: mirrorgooglecontainers/serve_hostname:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: hostname-lb-svc
  namespace: edgemesh-test
spec:
  selector:
    app: hostname-lb-edge
  ports:
    - name: http-0
      port: 12345
      protocol: TCP
      targetPort: 9376
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hostname-lb-svc
  namespace: edgemesh-test
spec:
  host: hostname-lb-edge
  trafficPolicy:
    loadBalancer:
      simple: RANDOM